name: Build NET

on:
  workflow_dispatch:
    
jobs:
  BuildDotNet:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3  

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1

      - name: Restore FSC Nugets
        uses: FH-Inway/FSC-PS-Actions/RestoreFSCNuget@restore-fsc-nugets
        with:
          version: '10.0.38'
          packagesDirectory: '${{ github.workspace }}/Project/D365FOAdminToolkit/packages'

      - name: Show files
        run: tree /F

      - name: Restore NuGet packages
        run: nuget restore Project/D365FOAdminToolkit/D365FOAdminToolkitNET/D365FOAdminToolkitNET.csproj -PackagesDirectory Project\D365FOAdminToolkit\packages

      - name: Build
        run: msbuild Project/D365FOAdminToolkit/D365FOAdminToolkitNET/D365FOAdminToolkitNET.csproj /p:VersionSuffix=pr /p:Configuration=Release /p:Version=0.0.0.${{ github.event.pull_request.number }} /p:InformationalVersion=0.0.0.${{ github.event.pull_request.number }}-pr

      - name: Upload D365FOAdminToolkitNET
        uses: actions/upload-artifact@v3
        with:
          name: D365FOAdminToolkitNET
          path: Project/D365FOAdminToolkit/D365FOAdminToolkitNET/bin/Release 